### 获取错误码
GET http://localhost:8000/system/error-code/get?id=1512820178886918146
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOjEsInVzZXJuYW1lIjoiYWRtaW4ifQ.S4j60adML6S0kTspW9ZnUrbPfbEMyPnbuh613Ab7Tz0

{
  "code": 200,
  "msg": null,
  "data": {
    "applicationName": "gateway-admin-bootstrap",
    "code": 1002018001,
    "message": "社交解绑失败，非当前用户绑定",
    "memo": "",
    "id": 1512820178886918146,
    "type": 1,
    "createTime": "2022-04-09T15:50:12.000+00:00"
  }
}

